trigger:
  paths:
    include:
      - infra/*

variables:
  backendAzureRmResourceGroupName: 'terraform-state-rg'
  backendAzureRmStorageAccountName: 'cosigwe6828'
  backendAzureRmContainerName: 'tfstate'
  backendAzureRmKey: 'devops-todo-neon.tfstate'      

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: '1.7.5'

- task: TerraformTaskV4@4
  displayName: 'Terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
    backendServiceArm: 'neon-serviceConnection'
    backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
    backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
    backendAzureRmContainerName: '$(backendAzureRmContainerName)'
    backendAzureRmKey: '$(backendAzureRmKey)'

- task: TerraformTaskV4@4
  displayName: 'Terraform plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
    environmentServiceNameAzureRM: 'neon-serviceConnection'
    commandOptions: '-var "database_url=$(database_url)"'

- task: TerraformTaskV4@4
  displayName: 'Terraform apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
    environmentServiceNameAzureRM: 'neon-serviceConnection'
    commandOptions: '-auto-approve -var "database_url=$(database_url)"'
